Flashcards
==========
Ciaran Downey <code@ciarand.me>
:toc:

NOTE: This forreals is not ready for anyone to use. That's not a "beta" warning
or whatever, that's a I'm-not-promising-this-will-compile-for-now warning.

[quote]
A tiny app to help you study

Getting started
---------------

For regular people:

. Figure out what operating system you're running and whether your machine has
  a 32-bit processor or 64-bit processor.

. Go to the https://github.com/ciarand/flashcards/releases[releases page] and
  choose the right package for your machine.

. Download it.

. Run it. Double clicking will work, or you can execute it on the command line:

[source,bash]
----
/wherever/you/put/it/flashcards
----

For nerds:

. `go get github.com/ciarand/flashcards`


Changing the cards
------------------
TODO

Using a different set of cards
------------------------------
TODO

License
-------
Copyright (c) 2015, Ciaran Downey <code@ciarand.me>

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
